name = "HashCode2014Solution"
uuid = "394669db-7213-4d5e-82a9-0a3784ac6128"
authors = ["Guillaume Dalle <22795598+gdalle@users.noreply.github.com>"]
version = "0.1.0"

[deps]
HashCode2014 = "7bbed249-721d-42ac-b1f6-7cf884be0fbe"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Aqua = "0.5"
Documenter = "0.27"
Graphs = "1.7"
HashCode2014 = "0.1"
HiGHS = "1"
JuMP = "1"
JuliaFormatter = "1"
ProgressLogging = "0.1"
julia = "1.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HashCode2014 = "7bbed249-721d-42ac-b1f6-7cf884be0fbe"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Documenter", "HashCode2014", "Graphs", "JuliaFormatter", "Test"]
